wip debugging rsyslog permissions

diff --git a/.github/workflows/reuse-build.yaml b/.github/workflows/reuse-build.yaml
--- a/.github/workflows/reuse-build.yaml
+++ b/.github/workflows/reuse-build.yaml
@@ -28,36 +28,36 @@ jobs:
           df -h
           sudo apt-get update
 
-      - name: Maximize free space
-        id: maximize-space
-        uses: jlumbroso/free-disk-space@main
-        with:
-          tool-cache: true
-          android: true
-          dotnet: true
-          haskell: true
-          large-packages: true
-          docker-images: true
-          swap-storage: true
+#      - name: Maximize free space
+#        id: maximize-space
+#        uses: jlumbroso/free-disk-space@main
+#        with:
+#          tool-cache: true
+#          android: true
+#          dotnet: true
+#          haskell: true
+#          large-packages: true
+#          docker-images: true
+#          swap-storage: true
 
-      - name: Freespace Check
-        shell: bash
-        run: |
-          df -h
-          REQUIRED_FREE_SPACE=25
-          free_space=$(df -h . | awk '{print $4}' | grep "G")
-          free_space="${free_space%G}"
-          if [ -z "$free_space" ]; then
-              echo "ERROR: free_space variable is empty or not set." >&2
-              exit 1
-          fi
-          df -h
-          echo "Free space (required): ${REQUIRED_FREE_SPACE} GB"
-          echo "Free space (available): ${free_space} GB"
-          if (( REQUIRED_FREE_SPACE > free_space )); then
-              echo "ERROR: Insufficient free space: ${free_space} GB available, ${REQUIRED_FREE_SPACE} GB required." >&2
-              exit 1
-          fi
+#      - name: Freespace Check
+#        shell: bash
+#        run: |
+#          df -h
+#          REQUIRED_FREE_SPACE=25
+#          free_space=$(df -h . | awk '{print $4}' | grep "G")
+#          free_space="${free_space%G}"
+#          if [ -z "$free_space" ]; then
+#              echo "ERROR: free_space variable is empty or not set." >&2
+#              exit 1
+#          fi
+#          df -h
+#          echo "Free space (required): ${REQUIRED_FREE_SPACE} GB"
+#          echo "Free space (available): ${free_space} GB"
+#          if (( REQUIRED_FREE_SPACE > free_space )); then
+#              echo "ERROR: Insufficient free space: ${free_space} GB available, ${REQUIRED_FREE_SPACE} GB required." >&2
+#              exit 1
+#          fi
 
       - name: Checkout
         uses: actions/checkout@v2
